import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Diego() {//Obligatorio export default
  return (
    <div className={styles.container}>
        
      <Head>
        <title>Create Next Apgggp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         ir al <a href="/about">About</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <h1>
            contact
        </h1>

      </main>


    </div>
  )
}
